# Generated by Django 4.2.3 on 2023-07-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='completed',
        ),
        migrations.AlterField(
            model_name='completion',
            name='date',
            field=models.DateField(verbose_name='Exercise Date'),
        ),
        migrations.AlterField(
            model_name='completion',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.exercise'),
        ),
    ]
